### ISSUE TITLE
CJK Support in IE8?

### ISSUE THREAD

**Issue by andrewplummer** [adobe-fonts/adobe-blank#6]
After testing out this font I've seen that in IE8 the .eot file correctly turns English characters blank but doesn't seem to support CJK. Additionally, the English characters are blank but still take up space, whereas standards browser render them as zero width.

I don't know too much about font specifics... is this something inherent to EOT files? Is it simply an impossibility?

**Comment by andrewplummer** [comment]
Yes, EOT seems to be the only format it supports. I understand your perspective that it's not worth supporting but I think I have a decent use case. I'm trying to use it to be able to detect font support in various browsers and Adobe Blank provides a great way to test that support. I'm not trying to do anything in IE specifically but it would be nice to handle cases for other people that still require this support.

**Comment by kenlunde** [comment]
I used the command-line [_ttf2eot_](http://code.google.com/p/ttf2eot/) tool to convert the TTF into an EOT. Doing a search suggested that some EOTs don't work as expected—or are not recognized at all—unless they are converted using _Microsoft WEFT_, which I cannot find, and which I couldn't use anyway, as I don't use Windows OS. If you are able to find this Microsoft tool, please try to use it to convert the TTF into an EOT. If the resulting EOT works, please provide it to me so that I can replace the one in this repository.
